/*
 * GibberishNameDetector
 *
 * Pass in a list of names and a Markov probability table
 * Returns names with positive score, negative score, final score, and 1/0 for pass/fail
 *
 * Depends on pre-built detector Markov chains
 *
 * Markov probability table includes:
 * - Threshold
 * - array of good probabilities
 * - array of bad probabilities
 * Generated by GibberishDetector.train goodProbability, badProbability Lists
 *
 * Final utils and flow:
 *
 * Create script-based probability markov chains
 *  - add negative lists markov chain builder based off CLDR keyboard maps and language
 *    - always include Latin-101 keyboard
 *    - add html, script, camelcase, .com names
 *  - add Collections writer to utils + threshold
 *  - add script detector module based off ICU UCD script in utils - script of line, throw out common
 *  - add alphabet builder, including accented chars
 *  - add probability value display to line check
 *  - auto-gibberish name is wrong punct in string, like email, html, script @ \w.\w http
 */
package GibberishNameDetector;

import com.ibm.icu.text.Normalizer2;
import com.ibm.icu.text.UnicodeSet;
import com.paypal.gibberishdetector.GibberishDetector;
import com.paypal.gibberishdetector.GibberishDetectorExtended;
import com.paypal.gibberishdetector.GibberishDetectorFactory;

/**
 *
 * @author mimckenna
 */
public class GibberishNameDetector {
	public static void main(String[] args) {

		String[] goodEnglishSentences = {
				"anderson",
				"boyd",
				"collins",
				"dudley-newson brenda",
				"edwards sandra",
				"ferguson vickie",
				"footman ursula",
				"gandy stacy",
				"hedgeman jerrika",
				"jenkins lanses",
				"lynom jackson beverly",
				"mcelhaney deaunna",
				"rainey renee",
				"billups wylie",
				"Moeneclaey",
				"Nazem",
				"Pagenkopf",
				"Zakarya"
		};
		String[] badEnglishSentences = {
				"2 chhsdfitoixcv",
				"Wm the 3rd",
				"fasdf asg ggd fhgkv",
				"qmdu poebc vuutkl jsupwre",
				"asdf asdf",
				"sam123",
				"mike@paypal.com",
				"http://unicode.org",
				"AAAAEEEESSSS",
				"AABCDEFGH",
				"JP",
				"GIJOE",
				"Mike.McKenna657",
				"eeeeeeeeeeeee",
				"Jane 8 Tau",
				"GIHOHOSD",
				"KAPTNBLAUBR",
				"KARLHEINZBHM",
				"GIJANE",
				"ZLATKO",
				"ÈIHÁÈKOVÁ DØÍMALOVÁ",
				"ŠŹOVÍÈKOVÁ ŠIMÁKOVÁ",
				"hjkhjkhjk",
				"qwerty",
				"asdfghjk",
				"zxcvbnm",
				"$$$$$$$",
				"nosdt in salwelawe",
				"☃☃☃☃",
				"Texin", "Ute", "May", "Stu", "Rex", "Sex", "aeioaueioaueaoiaeuaau"

		};
		// String alphabet = "abcdefghijklmnopqrstuvwxyz ";
		// Get alphabet from CLDR Exemplar characters for language group
		//String alphabet = " 0123456789!\"#&'()*,-./:;?@[]abcdefghijklmnopqrstuvwxyz\u00e8\u00A7\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E7\u00E8\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F1\u00F2\u00F3\u00F4\u00F6\u00F8\u00F9\u00FA\u00FB\u00FC\u00FF\u0101\u0103\u0113\u0115\u012B\u012D\u014D\u014F\u0153\u016B\u016D\u2010\u2013\u2014\u2018\u2019\u201C\u201D\u2020\u2021\u2026\u2032\u2033\u0300";
		String alphabet = " 0123456789!\"#&'()*,-./:;?@[]abcdefghijklmnopqrstuvwxyz\u00e8\u00A7\u00E0\u00E1\u00E2\u00E3\u00E4\u00E5\u00E6\u00E7\u00E8\u00E8\u00E9\u00EA\u00EB\u00EC\u00ED\u00EE\u00EF\u00F1\u00F2\u00F3\u00F4\u00F6\u00F8\u00F9\u00FA\u00FB\u00FC\u00FF\u0101\u0103\u0113\u0115\u012B\u012D\u014D\u014F\u0153\u016B\u016D\u2010\u2013\u2014\u2018\u2019\u201C\u201D\u2020\u2021\u2026\u2032\u2033\u0300";
		//UnicodeSet alphabet = new UnicodeSet(pattern);
//		String alphabet = normalizeKD(alphabet1);
		GibberishDetectorFactory factory = new GibberishDetectorFactory(GibberishDetectorExtended.class);

		/*
		 * Build and train probability matrix
		 * Use default values based on Census data if not passed in args
		 */
		GibberishDetector gibberishDetector = factory.createGibberishDetectorFromLocalFile2("en-training-data.txt",
				"en-good-names.txt", "badEnglish.txt", "en-alphabet.txt");
		//GibberishDetector gibberishDetector = factory.createGibberishDetectorFromLocalFile2("cs-train.txt",
		//									"cs-good.txt", "badEnglish.txt", "cs-alphabet.txt");
		// GibberishDetector negDetector = factory.createGibberishDetectorFromLocalFile2("keybd-en.txt",
		// "keybd-en-good.txt", "keybd-en-bad.txt", "keybd-en-alphabet.txt");

		System.out.println("------------");
		System.out.println("Test lines");
		System.out.printf("alphabet: %s%n", alphabet);
		System.out.println("------------");

		for (String line : goodEnglishSentences) {
			double goodProb = (gibberishDetector.getProbability(line) - gibberishDetector.threshold) * gibberishDetector.weight;
			// double negProb = (negDetector.getProbability(line) - negDetector.threshold) * negDetector.weight;
			double finalGibberish = goodProb ;//- negProb/2;

			System.out.printf("Gibberish: %s %f : %s\n",
					finalGibberish < 0 ? "TRUE  :" : "false : ",
							finalGibberish, line);
			System.out.printf("     Pos: %s   :  %f\n",
					gibberishDetector.isGibberish(line)? "yes" : "no ", goodProb);
			// System.out.printf("      Neg: %s   : %f\n\n",
			//         negDetector.isGibberish(line)? "no " : "yes", negProb);
		}

		System.out.println("------------");
		System.out.println("Test bad lines"); // Display the string.
		System.out.println("------------");

		for (String line : badEnglishSentences) {
			double goodProb = (gibberishDetector.getProbability(line) - gibberishDetector.threshold) * gibberishDetector.weight;
			// double negProb = (negDetector.getProbability(line) - negDetector.threshold) * negDetector.weight;
			double finalGibberish = goodProb; // - negProb/2;

			System.out.printf("Gibberish: %s %f : %s\n",
					finalGibberish < 0 ? "TRUE  :" : "false : ",
							finalGibberish, line);
			System.out.printf("     Pos: %s   :  %f\n",
					gibberishDetector.isGibberish(line)? "yes" : "no ", goodProb);
			// System.out.printf("      Neg: %s   : %f\n\n",
			//         negDetector.isGibberish(line)? "no " : "yes", negProb);
		}
	}
}
